/*
 * Copyright (c) 2015 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-4-Clause
 */

export const MODEM_OPENED = 'MODEM_OPENED';
export const MODEM_CLOSED = 'MODEM_CLOSED';
export const AVAILABLE_PORTS = 'AVAILABLE_PORTS';
export const MODEM_FLAGS_CHANGED = 'MODEM_FLAGS_CHANGED';
export const MOBILE_NETWORKS = 'MOBILE_NETWORKS';
export const SELECTED_MOBILE_NETWORK = 'SELECTED_MOBILE_NETWORK';
export const RSSI = 'RSSI';
export const REGISTRATION = 'REGISTRATION';
export const CELL_LOCATION = 'CELL_LOCATION';
export const PDP_CONTEXT = 'PDP_CONTEXT';
export const MODE_OF_OPERATION = 'MODE_OF_OPERATION';
export const FUNCTIONALITY = 'FUNCTIONALITY';
export const CURRENT_BAND = 'CURRENT_BAND';
export const SUPPORTED_BANDS = 'SUPPORTED_BANDS';
export const UICC_STATE = 'UICC_STATE';
export const PIN_CODE = 'PIN_CODE';
export const PIN_REMAINING = 'PIN_REMAINING';

export const SET_MAIN_VIEW = 'SET_MAIN_VIEW';
export const UPDATE_TERMINAL = 'UPDATE_TERMINAL';
export const TERMINAL_AUTO_SCROLL = 'TERMINAL_AUTO_SCROLL';
export const FLOW_CONTROL = 'FLOW_CONTROL';
export const CHART_UPDATE = 'CHART_UPDATE';
export const CHART_WINDOW = 'CHART_WINDOW';
export const CHART_WINDOW_RESET = 'CHART_WINDOW_RESET';
export const API_TOKEN_UPDATE = 'API_TOKEN_UPDATE';
export const AUTO_REQUESTS = 'AUTO_REQUESTS';
export const SIGNAL_QUALITY_INTERVAL = 'SIGNAL_QUALITY_INTERVAL';

export const UPDATE_SAVED_COMMANDS = 'UPDATE_SAVED_COMMANDS';
export const AUTO_DEVICE_FILTER_TOGGLED = 'AUTO_DEVICE_FILTER_TOGGLED';
